### PR TITLE
Clean up current compat and add medical compat

### PR DESCRIPTION
**Pull request by AACO**
This PR will:
- Cleanup the existing compatibility
- Add ACE medical handling of the Biofoam (best parts of elastic bandages + quikclot + morphine), Medigel (slightly worse biofoam), and medipack (PAK)

Notes:
- I import CBA macros in config.cpp, if that's a problem I can just pull the two macros I need out.
- Will only work properly with the current dev build

Questions:
- The existing ace ammo compat had:
`class OPTRE_M41_Rocket_HEAT_Guided: OPTRE_M41_Rocket_HEAT`
but the actual config has:
`class OPTRE_M41_Rocket_HEAT_Guided: M_Titan_AT`
so it's updating the base class (does it need to be fixed in the compat or the OpTre config?)

- Do we need to/should we be handling medi gel?

- I had to disable the heal/heal soldier scroll wheel menu items to make the medical items work okay without completely rebuilding them

- I'm currently just reducing pain and not doing any major drug effects (OD/BP/HR) with the biofoam because `future` is proper drug effects something we want?

- Are the effectiveness/reopening values okay?

- Do we need to use the MediKit in basic medical? Currently we cannot use the PAK in basic so we're not using the MediKit in basic

### CODE REVIEW

**Comment by Scorch052** [comment]
- Something I forgot to change. It should be inheriting from `M_Titan_AT` in both.

- Medigel and Biofoam should function the same.

- As long as they work fine in vanilla. Shouldn't be using them in ACE so if its only in the compat, no issue.

- Nope, none of that is necessary.

- MediKit is fine for Advanced only. Would it be possible to have it act as both a PAK and Surgical Kit?

**Comment by AACO** [comment]
Quick note, after talking to scorch MediGel should be a slightly less effective BioFoam

**Comment by AACO** [comment]
More notes for clarity
>As long as they work fine in vanilla. Shouldn't be using them in ACE so if its only in the compat, no issue.

Yeah the effect only kicks in with the compat PBO

>MediKit is fine for Advanced only. Would it be possible to have it act as both a PAK and Surgical Kit?

Surgical kit just removes [bandagedWounds](https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_surgicalKit_onProgress.sqf#L33) which the [PAK already does](https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_fullHealLocal.sqf#L33)
So we get that for free

**Comment by Scorch052** [comment]
Cool

**Comment by AACO** [comment]
* Fixed guided ammo base class
* Fixed Medikit -> Medkit naming
* Added medigel handling. ~75% effectiveness of bandage handling, ~50% wound reopening handling, ~25% pain management.

I would do a quick smoke test around existing compat, but this PR should be good to go

**Pull request merged**
